# NEVER EDIT this file.  It was generated and will be overwritten without
# notice upon regeneration of this application.  You have been warned.
package Apps::GENRanger;

use strict;
use warnings;

use Gantry qw{ -TemplateEngine=TT };

use JSON;
use Gantry::Utils::TablePerms;

our @ISA = qw( Gantry );


use Apps::Ranger::Model;
sub schema_base_class { return 'Apps::Ranger::Model'; }
use Gantry::Plugins::DBIxClassConn qw( get_schema );

#-----------------------------------------------------------------
# $self->namespace() or Apps::Ranger->namespace()
#-----------------------------------------------------------------
sub namespace {
    return 'Apps::Ranger';
}

#-----------------------------------------------------------------
# $self->init( $r )
#-----------------------------------------------------------------
sub init {
    my ( $self, $r ) = @_;

    # process SUPER's init code
    $self->SUPER::init( $r );

    $self->set_session_file( $self->fish_config( 'session_file' ) || '' );
    $self->set_username( $self->fish_config( 'username' ) || '' );
    $self->set_password( $self->fish_config( 'password' ) || '' );
    $self->set_service_url( $self->fish_config( 'service_url' ) || '' );
} # END init


#-----------------------------------------------------------------
# $self->set_session_file( $new_value )
#-----------------------------------------------------------------
sub set_session_file {
    my ( $self, $value ) = @_;

    $self->{ __session_file__ } = $value;
}

#-----------------------------------------------------------------
# $self->session_file(  )
#-----------------------------------------------------------------
sub session_file {
    my $self = shift;

    return $self->{ __session_file__ };
}

#-----------------------------------------------------------------
# $self->set_username( $new_value )
#-----------------------------------------------------------------
sub set_username {
    my ( $self, $value ) = @_;

    $self->{ __username__ } = $value;
}

#-----------------------------------------------------------------
# $self->username(  )
#-----------------------------------------------------------------
sub username {
    my $self = shift;

    return $self->{ __username__ };
}

#-----------------------------------------------------------------
# $self->set_password( $new_value )
#-----------------------------------------------------------------
sub set_password {
    my ( $self, $value ) = @_;

    $self->{ __password__ } = $value;
}

#-----------------------------------------------------------------
# $self->password(  )
#-----------------------------------------------------------------
sub password {
    my $self = shift;

    return $self->{ __password__ };
}

#-----------------------------------------------------------------
# $self->set_service_url( $new_value )
#-----------------------------------------------------------------
sub set_service_url {
    my ( $self, $value ) = @_;

    $self->{ __service_url__ } = $value;
}

#-----------------------------------------------------------------
# $self->service_url(  )
#-----------------------------------------------------------------
sub service_url {
    my $self = shift;

    return $self->{ __service_url__ };
}


#-----------------------------------------------------------------
# $self->do_main(  )
#-----------------------------------------------------------------
sub do_main {
    my ( $self ) = @_;

    $self->stash->view->template( 'main.tt' );
    $self->stash->view->title( 'Main Listing' );

    $self->stash->view->data( { pages => $self->site_links() } );
} # END do_main

#-----------------------------------------------------------------
# $self->site_links(  )
#-----------------------------------------------------------------
sub site_links {
    my ( $self ) = @_;

    return [
        { link => $self->app_rootp() . '/inventory', label => 'Inventory' },
    ];
} # END site_links

1;

=head1 NAME

Apps::GENRanger - generated support module for Apps::Ranger

=head1 SYNOPSIS

In Apps::Ranger:

    use base 'Apps::GENRanger';

=head1 DESCRIPTION

This module was generated by Bigtop (and IS subject to regeneration) to
provide methods in support of the whole Apps::Ranger
application.

Apps::Ranger should inherit from this module.

=head1 METHODS

=over 4

=item namespace

=item init

=item do_main

=item site_links

=item schema_base_class

=item session_file

=item set_session_file

=item username

=item set_username

=item password

=item set_password

=item service_url

=item set_service_url


=back

=head1 AUTHOR

root, E<lt>root@localdomainE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2010 root

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut

