package Apps::Ranger;

use strict;
use warnings;

our $VERSION = '0.07';

use base 'Apps::GENRanger';
use Apps::Ranger::VMware;
use Data::Dumper;

sub init {
    my ($self, $r) = @_;
    
    $self->SUPER::init($r);
    
    Apps::Ranger::VMware->new( $self->service_url,
                                    $self->session_path, 
                                    $self->credstore,
                                    $self->username,
                                    $self->password );
}

#-----------------------------------------------------------------
# $self->do_main(  )
#-----------------------------------------------------------------
# This method inherited from Apps::GENRanger

sub do_main {
    my ( $self ) = @_;

    my $poweredoff = 0;
    my $poweredon = 0;
    my $machines_ood = 0;
    my $machines_ok = 0;
    my $machines_no = 0;

    my $entity_views = Vim::find_entity_views( view_type => 'VirtualMachine' );
    
    $self->stash->view->template( 'inventory.tt' );
    $self->stash->view->title( 'Inventory Listing' );

    $self->stash->view->data( { entities => $entity_views } );
    
}

#-----------------------------------------------------------------
# $self->site_links(  )
#-----------------------------------------------------------------
# This method inherited from Apps::GENRanger


#-----------------------------------------------------------------
# $self->init( $r )
#-----------------------------------------------------------------
# This method inherited from Apps::GENRanger

1;

=head1 NAME

Apps::Ranger - the base module of this web app

=head1 SYNOPSIS

This package is meant to be used in a stand alone server/CGI script or the
Perl block of an httpd.conf file.

Stand Alone Server or CGI script:

    use Apps::Ranger;

    my $cgi = Gantry::Engine::CGI->new( {
        config => {
            #...
        },
        locations => {
            '/' => 'Apps::Ranger',
            #...
        },
    } );

httpd.conf:

    <Perl>
        # ...
        use Apps::Ranger;
    </Perl>

If all went well, one of these was correctly written during app generation.

=head1 DESCRIPTION

This module was originally generated by Bigtop.  But feel free to edit it.
You might even want to describe the table this module controls here.

=head1 METHODS

=over 4

=item get_orm_helper


=back


=head1 METHODS INHERITED FROM Apps::GENRanger

=over 4

=item namespace

=item init

=item do_main

=item site_links

=item schema_base_class

=item session_file

=item set_session_file

=item username

=item set_username

=item password

=item set_password

=item service_url

=item set_service_url


=back


=head1 SEE ALSO

    Gantry
    Apps::GENRanger
    Apps::Ranger::Inventory
    Apps::Ranger::VMware
    Apps::Ranger::VMware::ESX

=head1 AUTHOR

root, E<lt>root@localdomainE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2010 root

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut
