package Apps::Ranger::Model;
use strict; use warnings;

__PACKAGE__->load_classes( qw/
/ );

1;

=head1 NAME

Apps::Ranger::GENModel - regenerating schema for Apps::Ranger

=head1 SYNOPSIS

In your base schema:

    use base 'DBIx::Class::Schema';
    use Apps::Ranger::GENModel;

=head1 DESCRIPTION

This module was generated by Bigtop (and IS subject to regeneration).

=head1 DEPENDENCIES

    Gantry::Utils::DBIxClass

=head1 AUTHOR

root, E<lt>root@localdomainE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2010 root

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut
