package Apps::Ranger::Model;
use strict; use warnings;

use base 'DBIx::Class::Schema';

use Apps::Ranger::GENModel;

sub get_db_options {
    return { AutoCommit => 1 };
}

1;

=head1 NAME

Apps::Ranger::Model - schema class for Apps::Ranger

=head1 SYNOPSIS

In your base module:

    use Apps::Ranger::Model;
    sub schema_base_class { return 'Apps::Ranger::Model'; }
    use Gantry::Plugins::DBIxClassConn qw( get_schema );

=head1 DESCRIPTION

This module was generated by Bigtop.  But, feel free to edit it.  You
might even want to update these docs.

=over 4

=item get_db_options

The generated version sets AutoCommit to 1, this assumes that you will
do all transaction work via the DBIx::Class API.

=back

=head1 DEPENDENCIES

    Gantry::Utils::DBIxClass
    Apps::Ranger::GENModel

=head1 AUTHOR

root, E<lt>root@localdomainE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2010 root

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut
